### ISSUE TITLE
Error message: Parameter list too large, or call requires CDecl

### ISSUE THREAD

**Issue by borodin-devel** [Aldrin-John-Olaer-Manalansan/RA2YR-reMIXer#3] opened 2023-11-19 21:33 UTC
Tried to open MIX file that was marked **Recoverable** for both header and LMD. Received next error with all MIX files that I've tried (used "Recommended" method).

> Error: Parameter list too large, or call requires CDecl.
> 
> Specifically: 12
> 
> ▶	649: DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> 
> The current thread will exit.
> 
> Call stack:
> * (649) : [DllCall] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> * (649) : [reMIX_Level_3] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> * (319) : [Gui_ControlPanel_reMIXAllTargets_DoWork] reMIX_Level_%Gui_ControlPanel_DDL.Value%(Gui_ControlPanel_LV.GetText(A_Index,3))
> > Gui

**Comment by borodin-devel** [comment] 2023-11-19 21:38
Should I provide hex dump of file beginning (please write suitable size)?

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2023-11-19 23:20
> Tried to open MIX file that was marked **Recoverable** for both header and LMD. Received next error with all MIX files that I've tried (used "Recommended" method).
> 
> > Error: Parameter list too large, or call requires CDecl.
> > Specifically: 12
> > ▶	649: DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > The current thread will exit.
> > Call stack:
> > 
> > * (649) : [DllCall] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > * (649) : [reMIX_Level_3] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > * (319) : [Gui_ControlPanel_reMIXAllTargets_DoWork] reMIX_Level_%Gui_ControlPanel_DDL.Value%(Gui_ControlPanel_LV.GetText(A_Index,3))
> > 
> > > Gui


@borodin-devel share a download link here on your next post, which is the MIX File you tried to reMIX that produces this error, so that I can reproduce it. If it's a private file you don't wish for others to see, you can share it through gdrive with my email granted access aldrinjohnolaermanalansan@gmail.com .

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2023-11-20 13:03
> Tried to open MIX file that was marked **Recoverable** for both header and LMD. Received next error with all MIX files that I've tried (used "Recommended" method).
> 
> > Error: Parameter list too large, or call requires CDecl.
> > Specifically: 12
> > ▶	649: DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > The current thread will exit.
> > Call stack:
> > 
> > * (649) : [DllCall] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > * (649) : [reMIX_Level_3] DllCall("MSVCRT.dll\memcpy", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Ptr", File_Ptr, "UInt", File_Size)
> > * (319) : [Gui_ControlPanel_reMIXAllTargets_DoWork] reMIX_Level_%Gui_ControlPanel_DDL.Value%(Gui_ControlPanel_LV.GetText(A_Index,3))
> > 
> > > Gui

Hi @borodin-devel I cannot reproduce any error using the MIX file you've sent to me privately. The tool can reconstruct your MIX file without fail on my end. What Operating System are you booting at and what architecture does it run from?

**Comment by borodin-devel** [comment] 2023-11-20 13:09
Hello, @Aldrin-John-Olaer-Manalansan , my OS is Windows 10 Pro, standard x86-64 arch. Just downloaded the file, put it in another folder on C:\ drive and launched it. Tried elevated privileges too. Nothing more, nothing less. I presume it has static linkage with needed libraries and doesn't require additional DLLs to work. I can run Dependency Walker on it if you wish.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2023-11-20 15:36
> Hello, @Aldrin-John-Olaer-Manalansan , my OS is Windows 10 Pro, standard x86-64 arch. Just downloaded the file, put it in another folder on C:\ drive and launched it. Tried elevated privileges too. Nothing more, nothing less. I presume it has static linkage with needed libraries and doesn't require additional DLLs to work. I can run Dependency Walker on it if you wish.

NVM, I was able to reproduce it and the bug has been fixed. Download this version and test it again. if the problem still persists, post the concern here and reopen the issue.

Now Closing this issue assumed as [fixed](https://github.com/Aldrin-John-Olaer-Manalansan/RA2YR-reMIXer/commit/e4bea1d542c886c04811460c208ffa3edcd2429e).

**Comment by borodin-devel** [comment] 2023-11-20 23:12
One MIX file is marked as NOT RECOVERABLE for LMD (for no visible reason as it is from the same batch as the others). But recommended method is used.

Error: Parameter list too large, or call requires CDecl.

Specifically: 12

▶	610: DllCall("MSVCRT.dll\memset", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Int", 0xFF, "UInt", 12)

The current thread will exit.

Call stack:
*#1 (610) : [DllCall] DllCall("MSVCRT.dll\memset", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Int", 0xFF, "UInt", 12)
*#1 (610) : [reMIX_Level_3] DllCall("MSVCRT.dll\memset", "Ptr", reMIX_Area_Body_Ptr + reMIX_Area_Body_Size, "Int", 0xFF, "UInt", 12)
*#1 (327) : [Gui_ControlPanel_reMIXAllTargets_DoWork] reMIX_Level_%Gui_ControlPanel_DDL.Value%(Gui_ControlPanel_LV.GetText(A_Index,3))
> Gui

File in G-Drives archive.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2023-12-08 08:17
This ticket is now marked for UAT for 1 week. Test the latest build and report here if a problem connected to this ticket have been encountered.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2023-12-14 13:11
This issue is now assumed as Fixed.

Ticket Closed.

**Closed by Aldrin-John-Olaer-Manalansan** 2023-12-14 13:11 UTC
Labels: bug, ongoing UAT
